### PR TITLE
Add dependencies for pyodbc library

### PR DESCRIPTION
**Pull request by BuckAMayzing**
I tested this in the PR [here](https://github.com/StatesTitle/underwriter/pull/2468). Note the changed circleci config. Once this is merged, I'll revert that config change over there and continue along with API+ changes.

### CODE REVIEW

**Comment by khoistatestitle** [comment]
Did you try out this change, @BuckAMayzing?

**Review by markdoliner-doma — APPROVED** [review]
This change seems fine to me. As far as I know we only use it for running tests on Circle. It seems perfectly reasonable to have g++ installed in the Docker image used for "build_and_test"

**Comment by mdoliner-st** [comment]
I am curious about "Your image failed to build in Docker Hub," though. I can't view the details. I don't think I have a Docker Hub account associated with States Title.

**Comment by BuckAMayzing** [comment]
> Did you try out this change, @BuckAMayzing?

I did. It's why the PR [here](https://github.com/StatesTitle/underwriter/pull/2468) is passing

**Comment by BuckAMayzing** [comment]
> I am curious about "Your image failed to build in Docker Hub," though. I can't view the details. I don't think I have a Docker Hub account associated with States Title.

The details:

image

From what I can tell, this occurs often, but it's not clear to me why.

**Comment by mdoliner-st** [comment]
> From what I can tell, this occurs often, but it's not clear to me why.

Weird. It's true that there's no Dockerfile at the top level of this repo, assuming that's where it's looking. It should be looking in the `underwriter` directory.

**Comment by C-Saunders** [comment]
It's possible the build settings are off - you can supply Dockerhub with the path to the Dockerfile in the build settings. There isn't really any documentation about how paths are resolved or anything like that, so your best bet is probably to look at the settings for one of the builds that is working.

**Comment by C-Saunders** [comment]
It's possible the build settings are off - you can supply Dockerhub with the path to the Dockerfile in the build settings. There isn't really any documentation about how paths are resolved or anything like that, so your best bet is probably to look at the settings for one of the builds that is working.

**Comment by C-Saunders** [comment]
It's possible the build settings are off - you can supply Dockerhub with the path to the Dockerfile in the build settings. There isn't really any documentation about how paths are resolved or anything like that, so your best bet is probably to look at the settings for one of the builds that is working.

**Comment by C-Saunders** [comment]
It's possible the build settings are off - you can supply Dockerhub with the path to the Dockerfile in the build settings. There isn't really any documentation about how paths are resolved or anything like that, so your best bet is probably to look at the settings for one of the builds that is working.

**Pull request merged**
